### ISSUE TITLE
Transfer into year sub folder

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/rodeos-ingest#13]
Dependency:

- https://github.com/irods/irods_capability_automated_ingest/issues/151

**Comment by messersc** [comment]
I do currently solve this in bash before calling the actual ingest like so (i is the path to the flowcell dir):

```
        DIR=$(basename $i)
        YEAR=20${DIR::2}  # first two chars
        imkdir $TARGET
        imkdir $TARGET/$YEAR
        imkdir $TARGET/$YEAR/$DIR
```

and then point the ingest to the created collection.

Is this ok?

**Comment by trel** [comment]
you can save two round trips with `imkdir -p $TARGET/$YEAR/$DIR`
